### ISSUE TITLE
It's that time of the year ... 

### ISSUE THREAD

**Issue by pmmueller** [iandevlin/html5bones#17]
- update sample footer copyright date to 2016
- normalize.css is still at v3.0.2 I think, and therefore does *not* need an update ;-)

**Comment by iandevlin** [comment]
Done.

**Comment by MahmoudMaher0** [comment]
I don:t understand any thing , explain please.

2016-01-17 12:08 جرينتش+02:00, Ian Devlin <notifications@github.com>:

**Comment by iandevlin** [comment]
@MahmoudMaher0 You don't understand what, exactly? I am not sure what you are asking, and even if it is related to this closed issue?

**Comment by xewl** [comment]
"any thing" should've been self-explanatory. :') I'd ignore it.
