### ISSUE TITLE
Maybe remove ARIA Landmark Roles

### ISSUE THREAD

**Issue by pmmueller** [iandevlin/html5bones#18]
Maybe remove ARIA Landmark Roles from header, main & Co. 

See for example [Jeremy Keith's comment and Steve Faulkner's linked article](http://html5doctor.com/html-developers-please-consider/#comment-2065595)

**Comment by gtarnoff** [comment]
I'd be hesitant unless we could see IE stats. Maybe make a legacy branch for
older IE, mark it as "will not receive updates" but keeps the aria roles. Then
mark master as IE11+.

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.4.15&pv=9.2&source=email_footer_2]
On Mon, Jan 11, 2016 at 07:13, iandevlin/html5bones
<reply@reply.github.com>
wrote:
Maybe remove ARIA Landmark Roles from header, main & Co

See for example Jeremy Keith's comment and Steve Faulkner's linked article
[http://html5doctorcom/html-developers-please-consider/#comment-2065595]

**Comment by iandevlin** [comment]
I don't think they do any harm at the moment, so I will leave them in. But I will leave this issue open so it can be revisited later.

**Comment by weboverhauls** [comment]
Thanks for leaving in. Good for backwards compatibility.
